version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - main
image: Visual Studio 2022
environment:
  IGNORE_NORMALISATION_GIT_HEAD_MOVE: 1
    secure: AamTWVCKJufm2jab84spEoM0OrE87GyXhD8WflcEAV14fZtvVQni5vpEVT3f+OkE
nuget:
  disable_publish_on_pr: true
build_script:
  - pwsh: >-
      ./build.ps1 Environment
      
      ./build.ps1 Rebuild --verbosity Verbose
test: off
deploy_script:
  - pwsh: ./build.ps1 Publish --NugetApiKey $env:NugetApiKey --verbosity Verbose