version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - main
image: Visual Studio 2022
environment:
  # Workaround for https://github.com/GitTools/GitVersion/issues/1627
  IGNORE_NORMALISATION_GIT_HEAD_MOVE: 1
  NugetApiKey:
    secure: RR+ggAKwi1QNOtVC29N40t1Ah4PH6vclmNd2wiQ5D+lNWGWy73Wtiy+ur3WuS4gp
nuget:
  disable_publish_on_pr: true
build_script:
  - pwsh: ./build.ps1 Rebuild --verbosity Verbose
test: off
deploy_script:
  - pwsh: ./build.ps1 Publish --NugetApiKey $env:NugetApiKey --verbosity Verbose